### ISSUE TITLE
works with myricom plugin?

### ISSUE THREAD

**Issue by dopheide** [ncsa/bro-interface-setup#2]
Should I expect the bro-interface-setup script to work along with the myricom plugin?   Getting errors such as:

myricom::p1p1:4: ERROR while getting interface flags: No such device
SIOCSIFMTU: No such device

Given I didn't comment out the default interface commands, so it's still trying to use {interface}.

**Comment by JustinAzoff** [comment]
oooooh yeah, I can see how that would be a problem.  The plugin expects a literal interface name, so it won't work with that style of interface specification.

It should be possible to work around this problem though, what exactly is your interface value set to in the node.cfg?

I think I just need to see if it has a :: and take what's after that to get the 'real' interface?

so p1p1 -> p1p1 as-is, but myricom::p1p1 -> p1p1

**Comment by dopheide** [comment]
Right, it's exactly myricom::p1p1 in the config.

Dop

**Comment by JustinAzoff** [comment]
Ok.. update the plugin and try again. It should work now!

**Comment by dopheide** [comment]
Definitely getting closer, looks like some of it worked:

Failed to run command on localhost:
SIOCSIFFLAGS: Cannot assign requested address

-Dop

**Comment by JustinAzoff** [comment]
That is... weird.  Do you get the same error if you just run

    /sbin/ifconfig p1p1 up mtu 9000

which should be the command that the plugin is running.

Odd that we don't have this problem.... what SNF driver version are you using?

**Comment by dopheide** [comment]
Nope, that works fine.  It also keeps setting my mtu to 9216.

Using:  myri_snf-3.0.9.50782

-Dop

**Comment by JustinAzoff** [comment]
Oh right, yeah, the default mtu the plugin uses is 9216.

Is it the

    /sbin/ethtool -K p1p1 gro off lro off rx off tx off gso off

command that is throwing that error then?

**Comment by dopheide** [comment]
It actually throws a different error (that I don't see in the broctl deploy)

/sbin/ethtool -K p1p1 gro off lro off rx off tx off gso off
Cannot change large-receive-offload

I uninstalled the plugin to verify I'm not getting those errors from
someone else and it's definitely the plug causing them.   Any other
commands it could be trying to run?   (We can sit down later to look at
this system if you'd like).

-Dop

**Comment by JustinAzoff** [comment]
Yeah.. something weird is going on.

    interfacesetup.flags_command=/sbin/ethtool -K {interface} gro off rx off tx off gso off

may fix the 2nd error, but I'm not sure why you are seeing the first problem, especially since ifconfig works if you run it manually.

**Comment by JustinAzoff** [comment]
(and something weird is going on because we use myricom cards too, and I've been using those exact commands on our boxes for years)

**Comment by JustinAzoff** [comment]
Fixed in c0b13075cbf655d5c2d09e08e3edf460ae1d6d6b
